[package]
name = "blinded-sig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.10.6"
num-bigint = "0.4"
is-odd = "~1.1.0"
num-traits = "0.2.16"